### ISSUE TITLE
Has anyone tried using this with gogoinflight?

### ISSUE THREAD

**Issue by Arinerron** [PiMaker/Teletun#5]
Lol I'll try in a few days and get back to you all :)

**Comment by rsgrinko** [comment]
It's been a year and no reply :)

**Comment by Arinerron** [comment]
@rsgrinko flights have the free wifi with T-Mobile these days so I never ended up needing to try this again :p

**Comment by BGGexchange** [comment]
Google in bed 😆

**Comment by PiMaker** [comment]
This project is long abandonded. I will mark it as archived to prevent further issues from being created.
